version: '3.8'

services:
  mysql:
    build:
      context: .
      dockerfile: mysql.Dockerfile
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: a257814256
      MYSQL_DATABASE: web_scraping
      MYSQL_USER: root
      MYSQL_PASSWORD: a257814256
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_app
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: a257814256
      DB_NAME: web_scraping
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  mysql_data:
